#!/usr/local/bin/node

require('app-module-path').addPath(__dirname);
const program = require('commander');
const cli = require('cli/main');

function getOptions(arguments) {
    return program
        .version('0.1.0')
        .option('-t --target [url]', 'Targeted page.')
        .option('-d --depth [level]', 'Depth for recursive search.', 1)
        .option('-v --verbose', 'Show all logs.')
        .parse(arguments);
}

async function main() {
    const options = getOptions(process.argv);

    try {
        if (options.target) {
            await cli(options)
        }
    } catch (e) {
        throw e;
        //TODO('print it')
    }
}

main();
