#!/usr/bin/node

require('app-module-path').addPath(__dirname);
const program = require('commander');
const { Scrap } = require('lib');
const Tree = require('lib/tree');

function getOptions(arguments) {
    return program
        .version('0.1.0')
        .option('-t --target [url]', 'Targeted page.')
        .option('-d --depth [level]', 'Depth for recursive search.', 1)
        .option('-v --verbose', 'Show all logs.')
        .parse(arguments);
}

async function main() {
    const options = getOptions(process.argv);

    try {
        if (options.target) {
            // const scrap = new Scrap(options.target);
            // const pages = await scrap.start(options.depth);
            const tree = new Tree(options.target);
            console.log(tree.getLeafs());
            await tree.get();
            console.log(tree.getLeafs());
            await tree.get();
            console.log(tree.getLeafs());
        }
    } catch (e) {
        throw e;
        //TODO('print it')
    }
}

main();
