#!/usr/local/bin/node

require('app-module-path').addPath(__dirname);
const program = require('commander');
const cli = require('cli/main');

function getOptions(arguments) {
    return program
        .version('0.5.0')
        .option('-u, --url <url>', 'Targeted page.')
        .option('-d, --depth [level]', 'Depth for recursive search.', 1)
        .option('-t, --tree', 'Boolean to show tree.')
        .option('-v, --verbose', 'Show all logs.')
        .option('-c, --color', 'Show colorfull logs')
        .option('-f, --file <file>', 'write logs into file.')
        .parse(arguments);
}

async function main() {
    const options = getOptions(process.argv);
    try {
        if (!options.url) {
            console.log('  error: option `a-u, --url <url>` argument missing')
            process.exit(1);
        }
        await cli(options)
    } catch (e) {
        throw e;
        log.error('ERROR', e.message)
    }
}

main();
